Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-04, with the labels that each got.

#62 Update poetry.lock file
  poetry.lock
Labels: branch-main, verified, size/XXL, Approved-by-myakove

#67 Fix pre-commit flake8 config file call
  .pre-commit-config.yaml
Labels: branch-main, verified, size/XS, Approved-by-rnetser

#69 Flake remove exclude
  .flake8
  .pre-commit-config.yaml
Labels: branch-main, size/M, verified, Approved-by-myakove

#74 Hypershift - add OIDC creation and deletion
  tests/hypershift/test_hypershift.py
Labels: branch-main, size/S, verified, Approved-by-myakove, Approved-by-omrirh

#76 poetry update
  poetry.lock
  pyproject.toml
Labels: branch-main, verified, Approved-by-rnetser, size/XXL

#78 Use rosa-python-client
  poetry.lock
  tests/conftest.py
  tests/hypershift/test_hypershift.py
Labels: branch-main, size/M, verified, Approved-by-myakove, Approved-by-ankit-gautam23

#71 updating logger to simple-logger
  conftest.py
  pyproject.toml
  tests/cluster_upgrade/test_cluster_upgrade.py
  tests/cluster_upgrade/utils.py
  tests/conftest.py
  tests/hypershift/test_hypershift.py
  tests/managed_services/test_app_services.py
  tests/ocm_client/test_ocm_client.py
  utilities/infra.py
  utilities/logger.py
  utilities/pytest_utils.py
Labels: size/L, branch-main, verified, Approved-by-myakove
