Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-06, with the labels that each got.

#160 Fix rosa execute
  tests/conftest.py
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XS, Approved-by-myakove, can-be-merged

#162 update poetry
  poetry.lock
Labels: size/L, branch-main, verified

#197 Update tests rosa exec
  README.md
  poetry.lock
  tests/conftest.py
  tests/global_config.py
  tests/hypershift/test_hypershift.py
  tests/managed_services/conftest.py
  utilities/infra.py
Labels: size/L, branch-main, verified, Approved-by-myakove, can-be-merged
