Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-08, with the labels that each got.

#319 Add openshift ci data collector yaml
  conftest.py
  data-collector-openshift-ci.yaml
  poetry.lock
  pyproject.toml
Labels: size/L, branch-main, verified, ApprovedBy-myakove

#332 Remove base python from tox and remove unneeded envs
  scripts/code_check/unused_code.py
  tox.ini
Labels: branch-main, verified, size/XS, can-be-merged, ApprovedBy-rnetser

#346 Use openshift-installer for cluster creation and deletion
  .gitignore
  conftest.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/hypershift/manifests/setup-vpc.tf
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XXL, can-be-merged, ApprovedBy-myakove

#359 Do not exit pytest on multi-cluster sanity
  tests/cluster_sanity/test_cluster_sanity.py
  tests/managed_services/test_app_services.py
  utilities/infra.py
Labels: branch-main, size/S, verified, can-be-merged, ApprovedBy-myakove
