Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-11, with the labels that each got.

#508 Update pre-commit with ruff
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  conftest.py
  poetry.lock
  pyproject.toml
  scripts/code_check/unused_code.py
  tests/cluster_sanity/test_cluster_sanity.py
  tests/cluster_upgrade/conftest.py
  tests/cluster_upgrade/test_cluster_upgrade.py
  tests/cluster_upgrade/utils.py
  tests/hypershift/test_hypershift.py
  tests/managed_services/conftest.py
  tests/managed_services/mas_debezium/conftest.py
  tests/managed_services/mas_debezium/consumer_pod.py
  tests/managed_services/mas_debezium/test_mas_debezium.py
  utilities/pytest_utils.py
Labels: branch-main, verified, size/XXL, can-be-merged, approved-rnetser

#514 flake8-plugins pin to version
  .pre-commit-config.yaml
Labels: branch-main, verified, size/XS, can-be-merged, approved-rnetser

#459 Adding ACM Observability tests
  pytest.ini
  tests/acm_observability/README.md
  tests/acm_observability/conftest.py
  tests/acm_observability/test_acm_observability.py
  tests/global_config.py
Labels: size/L, branch-main, verified, can-be-merged, approved-myakove, commented-myakove, approved-rnetser

#524 Refactor `Dockerfile`, add `.dockerignore`
  .dockerignore
  Dockerfile
  pyproject.toml
  setup.py
Labels: branch-main, size/S, verified, can-be-merged, approved-rnetser

#531 Add sanity_single marker for single-cluster OCP sanity tests and remove kafka tests
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/cluster_sanity/test_cluster_sanity.py
  tests/managed_services/conftest.py
  tests/managed_services/mas_debezium/conftest.py
  tests/managed_services/mas_debezium/constants.py
  tests/managed_services/mas_debezium/consumer_pod.py
  tests/managed_services/mas_debezium/test_mas_debezium.py
  tests/managed_services/test_app_services.py
Labels: branch-main, verified, size/XXL, can-be-merged, approved-myakove, commented-rnetser
