Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-03, with the labels that each got.

#51 get_ocm_client: strip token to remove new line
  utilities/infra.py
Labels: branch-main, verified, size/XS, Approved-by-rnetser, Approved-by-omrirh

#55 Hypershift tests
  .dockerignore
  .gitignore
  .markdownlint.yaml
  .markdownlintignore
  .pre-commit-config.yaml
  README.md
  builder/Dockerfile
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/cluster_upgrade/conftest.py
  tests/conftest.py
  tests/global_config.py
  tests/hypershift/manifests/setup-vpc.tf
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XXL

#58 Hypershift install operator
  poetry.lock
  tests/hypershift/test_hypershift.py
Labels: branch-main, size/S, verified, Approved-by-myakove, hold
