Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2023-05, with the labels that each got.

#83 Update poetry
  poetry.lock
  pyproject.toml
Labels: size/L, branch-main, verified

#85 Update image path and name
  Makefile
  builder/Dockerfile
Labels: branch-main, size/S, verified, Approved-by-myakove

#89 Hypershift cluster install - get Hyper target version from ROSA
  poetry.lock
  pyproject.toml
  tests/hypershift/test_hypershift.py
Labels: size/L, branch-main, verified, Approved-by-myakove, Approved-by-omrirh

#94 Hypershift install cluster -a dd region to ROSA oidc-config cmd
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XS, Approved-by-myakove

#96 Use rosa-python-client from pipy and update poetry
  poetry.lock
  pyproject.toml
Labels: branch-main, size/M, verified

#104 Remove -y and --mode auto from commands
  poetry.lock
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XS, Approved-by-myakove

#110 poetry update
  poetry.lock
Labels: size/L, branch-main, verified

#132 update poetry
  poetry.lock
Labels: size/L, branch-main, verified

#134 Fix dockerfile
  .dockerignore
  Dockerfile
  Makefile
Labels: branch-main, verified, size/XS, Approved-by-rnetser, Approved-by-omrirh, can-be-merged
