Repository RedHatQE/managed-services-integration-tests, pull requests merged in 2024-01, with the labels that each got.

#672 User timeout-sampler module
  pyproject.toml
  tests/cluster_upgrade/utils.py
  tests/ocm_client/test_ocm_client.py
Labels: branch-main, verified, size/XS, can-be-merged, approved-myakove

#693 Update poetry
  poetry.lock
Labels: branch-main, size/M, verified, can-be-merged, approved-rnetser

#739 Update poetry openshift-python-wrapper
  poetry.lock
  pyproject.toml
Labels: size/L, branch-main

#818 Update hypershift tests to use cloud-tools for getting AWS region
  tests/hypershift/test_hypershift.py
Labels: branch-main, verified, size/XS, can-be-merged, approved-myakove
